version: '3.7'

services:

  opensearch:
    image: opensearchproject/opensearch:1.2.0
    restart: unless-stopped
    networks:
      - opensearch
    container_name: opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./os/data:/usr/share/opensearch/data
      - ./os/config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g

  dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    restart: unless-stopped
    container_name: dashboards
    depends_on:
      - opensearch
    networks:
      - opensearch
    ports:
      - '5601:5601'
    expose:
      - '5601'
    environment:
      - OPENSEARCH_PASSWORD=Endsumme273!
      - OPENSEARCH_URL=https://opensearch:9200
      - OPENSEARCH_HOSTS=https://opensearch:9200

networks:
  opensearch:
